### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by ghost** [mido3ds/JetSimulator#1]
Is possible build it under Linux?

What  hardware/platform requirements are?

**Comment by mido3ds** [comment]
Yes it builds on linux. Any pc from 2005 and up can run it.

Keep in mind its not complete, its more of a proof of concept for opengl graphics and animation than a game

You are welcome if you want to contribute.

**Comment by ghost** [comment]
> Keep in mind its not complete

Oh, I see.

FTR, I just user of *YSFlight*, but it's not fully open-source (freeware & partially opensource)

- https://ysflight.org
  - https://github.com/captainys/public (YSFlight developer repo)
  - https://github.com/ysflight-opensource (various opensource tools for YSFlight)

So, I just try find good opensource alternative (in active development) to YSFlight (as YSFLight development activity is low) for such PC as "pc from 2005", because FlightGear is too heavy for my PC from 2008 ;-)

P.S.: May I ask you, what you think about *MScSim*?

- http://marekcel.pl/?lang=en&page=mscsim
  - https://github.com/marek-cel/mscsim

**Comment by mido3ds** [comment]
MScSim looks more active in development than this, but i didn't  try it
tbh. Plus it has achieved a lot in the physics.

This project barely moves the plane. Its more of a graphics  tutorial's
mini-project rather than a simulation.

Unless you want to design and implement the physics part from scratch,
MScSim sounds better to contribute to.

app4soft <notifications@github.com> schrieb am So., 1. Dez. 2019, 1:28
vorm.:

**Comment by ghost** [comment]
Thanks!
